### ISSUE TITLE
Unable to build component with other world

### ISSUE THREAD

**Issue by TiejunMS** [bytecodealliance/wasi-nn#103]
I was building a module component using wit_bindgen to a world with exports. This component also depends on wasi-nn crate. It works while compiling it to WASM module. But it fails to compile into WASM component. I tried two ways to build WASM component but both failed. The commands are,
1. cargo build plus wasm-tools
    ```
    cargo build --target wasm32-wasip1 
    wasm-tools component new xxx.wasm -o yyy.wasm --adapt wasi_snapshot_preview1.reactor.wasm
    ```
1. cargo component
    ```
    cargo component build
    ``` 

The compiler error I got is,
```
error: failed to decode world from module

Caused by:
    0: module was not valid
    1: module requires an import interface named `wasi_ephemeral_nn`
```

I was able to build my component if I switched to wit_bindgen for wasi-nn. But I really like the way to include wasi-nn as a crate which hides all the details. Is there any plan to upgrade this crate to fix this issue? Thanks in advance!

**Comment by abrown** [comment]
At some point I had considered doing that but IIRC I felt like using wit-bindgen was easy enough. But, if you're interested in adding component support, I will gladly review that PR!

**Comment by TiejunMS** [comment]
Thanks for your quick response! Here is the PR: #104 
The example is replaced with the one from wasmtime repo: [classification-component-onnx](https://github.com/bytecodealliance/wasmtime/tree/main/crates/wasi-nn/examples/classification-component-onnx)

**Comment by TiejunZhou-CN** [comment]
Close as PR completed.
