### ISSUE TITLE
Troubleshoot AssemblyScript performance

### ISSUE THREAD

**Issue by abrown** [bytecodealliance/wasi-nn#12]
Why is the AssemblyScript example slower than the Rust version? There may be additional things on the Wasm side that could make the execution time faster. E.g., I noticed that loading the big weights files with `readBytes` seemed to take 20-25 seconds (a `as-wasi` issue?).

**Comment by MaxGraey** [comment]
[`sort`](https://github.com/bytecodealliance/wasi-nn/blob/main/assemblyscript/assembly/example.ts#L60) may be a problem. Using Weak Heap Sorting algorithm isn't stable while ECMAScript currently specify it should be stable. That's why we currently fallback to simple insertion sort for all references. It may be a problem for huge size of entries (> 1k)

**Comment by MaxGraey** [comment]
Also as-wasi uses `push` for (read/readAll)[https://github.com/jedisct1/as-wasi/blob/master/assembly/as-wasi.ts#L399]. Recently we fixed some huge [perf regression](https://github.com/AssemblyScript/assemblyscript/pull/1841) which relate to buffer's growing for `Array#push`. So I recommend update to `v0.18.31`

**Comment by brianjjones** [comment]
@MaxGraey Thanks for the heads up, it does run several seconds faster with that fix.

**Comment by MaxGraey** [comment]
this issue also [will be fixed soon](https://github.com/AssemblyScript/assemblyscript/pull/1904)

**Comment by abrown** [comment]
@MaxGraey, just wanted to say thanks for tracking this project and looking into these AssemblyScript issues. Let us know if you have any suggestions anywhere! (E.g., hope we're doing "the right thing" to get pointers [here](https://github.com/bytecodealliance/wasi-nn/blob/main/assemblyscript/assembly/as-wasi-nn.ts#L18-L22)).

**Comment by MaxGraey** [comment]
> (E.g., hope we're doing "the right thing" to get pointers here).

Arrays and TypedArrays have special property for point to started data called `dataStart` so you could use this:
```ts
// @ts-ignore: decorator
@inline 
function getArrayPtr<T>(data: T[]): usize {
    return data.dataStart;
}

// @ts-ignore: decorator
@inline 
function getTypedArrayPtr<T>(data: ArrayBufferView): usize {
    return data.dataStart; // it also take into account data.byteOffset
}
```

**Comment by abrown** [comment]
Good to know! I think had read somewhere (or deduced from https://github.com/AssemblyScript/assemblyscript/issues/743) that it was an unstable, undocumented thing. But now I actually see it in the [the docs](https://www.assemblyscript.org/memory.html#arraybufferview-layout) so it looks like we can simplify a bit.

**Comment by MaxGraey** [comment]
@abrown 0.19.7 now contain new stable sorting algorithm. So [this](https://github.com/bytecodealliance/wasi-nn/issues/12#issuecomment-814415477) should be fixed
