### ISSUE TITLE
Document engine flags for enabling wasi-nn

### ISSUE THREAD

**Issue by abrown** [bytecodealliance/wasi-nn#35]
The documentation does not make it clear that currently one must build Wasmtime with a special flag `--features wasi-nn` in order to enable the wasi-nn features. This is present in the [GitHub workflow](https://github.com/bytecodealliance/wasi-nn/blob/main/.github/workflows/main.yaml#L44) but it should be made explicit somewhere (perhaps in the top-level README and linked to from the `as` and `rust` READMEs?).

**Comment by abrown** [comment]
The `--features wasi-nn` flag will no longer be necessary once the next version of Wasmtime is released (v0.27.0). After https://github.com/bytecodealliance/wasmtime/pull/2859, wasi-nn can be enabled by passing the `--wasi-modules=experimental-wasi-nn` flag at runtime. After the next Wasmtime release, we should:
 - document that the `--wasi-modules` flag is necessary, 
 - update [this project's CI](https://github.com/bytecodealliance/wasi-nn/blob/main/.github/workflows/main.yaml#L42) to use the newer version of Wasmtime
 - and update the `build.sh` script to use the `--wasi-modules` flag.

**Comment by brianjjones** [comment]
Docs have been updated. And the CI uses the build.sh script to test, and that script has been updated with the needed flags.
