### ISSUE TITLE
Add PyTorch backend for `wasi-nn` crate

### ISSUE THREAD

**Issue by gusye1234** [bytecodealliance/wasi-nn#62]
Hi, I'm trying to implement a PyTorch backend for `wasi-nn`, and want to write a demo in rust.
I hope I can use the `wasi-nn` crate in my project, but it seems don't have a backend flag for PyTorch.

Should we add one? maybe one more line here:
https://github.com/bytecodealliance/wasi-nn/blob/bc63931e0dac2a63533b802980263aee291ed6a4/rust/src/generated.rs#L41
`pub const GRAPH_ENCODING_TORCH: GraphEncoding = 1; `

**Comment by abrown** [comment]
Makes sense to me; you may also want to submit a similar change up in the [spec repository](https://GitHub.com/webassembly/wasi-nn) as well.

**Comment by abrown** [comment]
This should be resolved by #65.
