### ISSUE TITLE
bash scripts using mapdir

### ISSUE THREAD

**Issue by TAOFOR4** [bytecodealliance/wasi-nn#99]
Hi,

I noticed the wasmtime cli flags have been redesigned in https://github.com/bytecodealliance/wasmtime/issues/6741. But the bash script here seems to still be using the old ones. Maybe it's better to update them.

**Comment by abrown** [comment]
Sure! You want to take a stab at this change?

**Comment by TAOFOR4** [comment]
> Sure! You want to take a stab at this change?

Sure, my pleasure.
